# Generated by Django 4.2.5 on 2023-11-22 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_product_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='price',
            new_name='wins',
        ),
    ]
